### ISSUE TITLE
Consider adjusting approach for resizing image

### ISSUE THREAD

**Issue by JoshVarty** [JoshVarty/KaggleClouds#19]
Our current approach alters the aspect ratio of our images. This seems like it would be harmful.

```
Current:
  Input: 	(350, 525)
  Resize	(352, 544)

  Output: 	(176, 272)
  Resize: 	(350, 525)


Goal:
  Input: 	(350, 525)
  Pad to	(352, 544)

  Output: 	(176, 272)
  Resize: 	(352, 544)
  Crop: 	(350, 525)
```
